  
language: java
jdk:
- oraclejdk9
services:
- mysql
dist: trusty
sudo: required
deploy:
  provider: heroku
  api_key:
    secure: "a6db0b66-088d-49e8-8f89-a99b52c7a23b"
     app: myaapp233f
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
- mysql -u root -e 'CREATE DATABASE empleado;'
- mysql -u root -e "CREATE USER 'sa'@'localhost' IDENTIFIED BY 'sa';"
- mysql -u root -e "GRANT ALL ON empleado.* TO 'sa'@'localhost';"
before_install:
- chmod +x mvnw